---
# (c) 2021 Ansible Project
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: Install dependencies
  package:
    name: "{{ aggregator_required_packages }}"
    state: present

- name: Install gems for rss and pluto planet aggregator
  community.general.gem:
    name: "{{ item }}"
    state: present
    # https://github.com/ansible-collections/community.general/issues/3259
    user_install: no
  # gem doesn't support providing a list to name
  loop: "{{ aggregator_required_gems }}"

- name: Create directory for pluto files
  file:
    path: "{{ aggregator_lib_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create configuration file
  template:
    src: planet.ini.j2
    dest: "{{ aggregator_lib_dir }}/planet.ini"
    owner: root
    group: root
    mode: 0644

- name: Create build directory
  file:
    path: "{{ aggregator_www_dir }}"
    state: directory
    owner: root
    group: root
    setype: httpd_sys_content_t
    mode: 0755

- name: Do a first build
  command: pluto build --output {{ aggregator_www_dir }}
  args:
    creates: "{{ aggregator_www_dir }}/planet.html"
    chdir: "{{ aggregator_lib_dir }}"

- name: Set up a cron to build updates on a regular basis
  cron:
    name: "pluto-rss-update"
    special_time: hourly
    job: "cd {{ aggregator_lib_dir }}; pluto build --output {{ aggregator_www_dir }} | tee | systemd-cat -t 'pluto-rss-update' -p info"

- name: Set up nginx configuration
  template:
    src: feed-aggregator.conf.j2
    dest: "/etc/nginx/conf.d/{{ aggregator_fqdn }}.conf"
  register: _nginx_conf

- name: Restart nginx if necessary
  service:
    name: nginx
    state: restarted
  when: _nginx_conf is changed

- name: Ensure nginx is started and enabled
  service:
    name: nginx
    state: started
    enabled: yes
